(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("die-hard",
{ "compressionlevel":-1,
 "height":100,
 "infinite":true,
 "layers":[
        {
         "chunks":[
                {
                 "data":"KLUv\/WAAA20CANQCHAAAAAYAAAAHAAAAGAAAABk7JAAAACUAAAA2AAAANwAAADg6WUIAAABDVlg7DCBwgnMPPF\/Jku4MGxtvXTYCz9y\/sXYHHTzdn3tE",
                 "height":16,
                 "width":16,
                 "x":-48,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA8UBALAaAAAAGAAAABkbOzo2AAAANzlZWFc7D6CgcNoBwAJEDzxVJqy6+Wua8agVv3NFc3\/OKPkyGck\/",
                 "height":16,
                 "width":16,
                 "x":-32,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA3UCAJLFCxFgGQp0E2F8LI7CCMGzOU0Beq26FR2iPl26nD\/Ijzdnvlx50owDZy9OfLjw4PcLCwA8QZUdAT+Nfsn6pjmQb0fCVEY3VB4gEz10Tw==",
                 "height":16,
                 "width":16,
                 "x":-16,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA2UCAHKFCxFweQmQ8bXhUNjXeiFKgAfL\/9KjQ5\/+3KGqIz9ufHlx4soTpvm7e2NfDw4IHwIKAC2hAgcmGQRwM7nZdT+zu3b9u5n9zI7NuSw=",
                 "height":16,
                 "width":16,
                 "x":0,
                 "y":-16
                }],
         "compression":"zstd",
         "encoding":"base64",
         "height":16,
         "id":2,
         "name":"Tile Layer 2",
         "opacity":1,
         "startx":-48,
         "starty":-16,
         "type":"tilelayer",
         "visible":true,
         "width":64,
         "x":0,
         "y":0
        }, 
        {
         "chunks":[
                {
                 "data":"KLUv\/WAAA70BAOD7AQAA\/AEAXwAAAHcBGwIAABwCAH0AOwIAADybCiBQQ4XGARkrgAAQUt+hdRCsYHibrZRbGAE=",
                 "height":16,
                 "width":16,
                 "x":-48,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA00CANQCAADqAQBfdwEAALUAAAC2AAAAtwAKAgB90wAAANQAAADVKpvxAAAA8gAAAPMACgA\/cRVCd0Oo2c5OzuwE+Aac1Jf4gj82gAU=",
                 "height":16,
                 "width":16,
                 "x":-32,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA60AAEh4AQBfAH0AmwAEEABLKzwJT8KaQw==",
                 "height":16,
                 "width":16,
                 "x":-16,
                 "y":-16
                }, 
                {
                 "data":"KLUv\/WAAA\/0AAEh4AQBfAH0AmwAIgPACdyFBJSDjHIAZ5ziKAZzMIAU=",
                 "height":16,
                 "width":16,
                 "x":0,
                 "y":-16
                }],
         "compression":"zstd",
         "encoding":"base64",
         "height":16,
         "id":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "startx":-48,
         "starty":-16,
         "type":"tilelayer",
         "visible":true,
         "width":64,
         "x":0,
         "y":0
        }],
 "nextlayerid":3,
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"left-down",
 "tiledversion":"1.4.1",
 "tileheight":16,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/..\/sprites\/p5\/die-hard-tileset.tsx"
        }, 
        {
         "firstgid":361,
         "source":"..\/..\/sprites\/p5\/die-hard-firniture.tsx"
        }],
 "tilewidth":16,
 "type":"map",
 "version":1.4,
 "width":100
});